@Testing = https://localhost:7035


POST {{Testing}}/api/Deltagare
Content-Type: application/json
{
         "Email":"Email@a.b",
         "Firstname":"Testing",
         "Middlename":"MiddlenameTest",
         "Lastname":"Lastname",
         "Phonenumber":"123456789"
}

###
