
@Testing = https://localhost:7035


POST {{Testing}}/api/Deltagare
Content-Type: application/json
{
         "Firstname": "Him Doe",
         "Middlename": "Doe",
         "Lastname": "Doe",
         "Email": "look.doe@example.com",
         "Phonenumber": "123456789"
}

###

POST {{Testing}}/api/Larare
Content-Type: application/json
{
         "Email" : "Did@doe@exemple.com",
         "Firstname": "Him Doe",
         "Middlename": "Doe",
         "Lastname": "Doe",
         "Kompentens": "IT"
}

###

POST {{Testing}}/api/Ort
Content-Type: application/json
{
         "Ortnamn" : "Helsingborg"
}

###

POST {{Testing}}/api/Kurs
Content-Type: application/json
{
         "Kurskod" : "FF22",
         "Kursnamn": "IT Höst",
         "Description": "IT kurs under hösten 202?"
}

###

POST {{Testing}}/api/Kurstillfalle
Content-Type: application/json
{
          "Kurskod" : "FF40",
          "Startdatum": "2022-12-31T23:59:59Z",
          "Slutdatum" : "2022-12-31T23:59:59Z",
          "Maxseats": "40",
          "OrtId" : "019c2ddc-f3c0-7961-84d5-7103d62c4776",
          "LarareEmail" : "test@exemple.com"
}

###

POST {{Testing}}/api/KursRegi
Content-Type: application/json
{
          "KursRegiId" : "f1e613ed-4797-4e36-b6b5-d262f900895c",
          "Antagen" : "ebd4628c-e1ea-4f6a-830c-191daba8af9c",
          "RegistrationDate" : "2022-12-31T23:59:59Z",
          "Status" : "Open"
}

###