
@Testing = https://localhost:7035


POST {{Testing}}/api/Deltagare
Content-Type: application/json
{
         "Firstname": "Him Doe",
         "Middlename": "Doe",
         "Lastname": "Doe",
         "Email": "look.doe@example.com",
         "Phonenumber": "123456789"
}

###

POST {{Testing}}/api/Larare
Content-Type: application/json
{
         "Email" : "Did@doe@exemple.com",
         "Firstname": "Him Doe",
         "Middlename": "Doe",
         "Lastname": "Doe",
         "Kompentens": "IT"
}

###

POST {{Testing}}/api/Ort
Content-Type: application/json
{
         "Ortnamn" : "Helsingborg"
}

###

POST {{Testing}}/api/Kurs
Content-Type: application/json
{
         "Kurskod" : "FF40",
         "Kursnamn": "IT Höst",
         "Description": "IT kurs under hösten 202?"
}

###

POST {{Testing}}/api/Kurstillfalle
Content-Type: application/json
{
          "Kurskod" : "FF40",
          "Startdatum": "2022-12-31T23:59:59Z",
          "Slutdatum" : "2022-12-31T23:59:59Z",
          "Maxseats": "40",
          "OrtId" : "1"
}

###

POST {{Testing}}/api/KursRegi
Content-Type: application/json
{
          "RegiID" : "eb3a35a6-dca7-4981-a2ac-33c3102941f5",
          "Antagen" : "9336f225-1d71-461d-8ca6-878cbb341fe5",
          "RegistrationDate" : "2022-12-31T23:59:59Z",
          "Status" : "Open"
}

###