CREATE TABLE Kurs (
  kurskod 				text 	PRIMARY KEY NOT NULL,
  namn 					text 	NOT NULL,
  beskrivning 			text 	NOT NULL
);

CREATE TABLE Ort (
  ort_id 				INT 	GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  namn					text 	UNIQUE NOT NULL
);

CREATE TABLE Deltagare (
  email 				text 	PRIMARY KEY NOT NULL,
  fornamn 				text 	NOT NULL,
  mellannamn 			text 	NOT NULL,
  efternamn 			text 	NOT NULL,
  telefonnummer 		text 	NOT NULL
);

CREATE TABLE Larare (
  email 				text 	PRIMARY KEY NOT NULL,
  fornamn 				text 	NOT NULL,
  mellannamn 			text 	NOT NULL,
  efternamn 			text 	NOT NULL,
  kompetens_omrade 		text 	NOT NULL
);

CREATE TABLE Kurstillfalle (
  kurstillfalle_id 		INT 	GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kurskod 				text 	NOT NULL,
  ort_id 				int 	NOT NULL,
  max_platser			int 	NOT NULL,
  start_Datum 			date 	NOT NULL,
  slut_Datum 			date 	NOT NULL
);

CREATE TABLE Kursregistrering (
  delatagare_email 		text 	NOT NULL,
  kurstillfalle_id 		int 	NOT NULL,
  regisretings_Datum 	date 	NOT NULL,
  status 				text 	NOT NULL,

  
  PRIMARY KEY (delatagare_email, kurstillfalle_id)
);

CREATE TABLE KurstillfalleLarare (
  larare_email 			text 	NOT NULL,
  kurstillfalle_id 		int 	NOT NULL,

  
  PRIMARY KEY (larare_email, kurstillfalle_id)
);

ALTER TABLE Kurstillfalle ADD FOREIGN KEY (kurskod) REFERENCES Kurs (kurskod);

ALTER TABLE Kurstillfalle ADD FOREIGN KEY (ort_id) REFERENCES Ort (ort_id);

ALTER TABLE Kursregistrering ADD FOREIGN KEY (delatagare_email) REFERENCES Deltagare (email);

ALTER TABLE Kursregistrering ADD FOREIGN KEY (kurstillfalle_id) REFERENCES Kurstillfalle (kurstillfalle_id);

ALTER TABLE KurstillfalleLarare ADD FOREIGN KEY (larare_email) REFERENCES Larare (email);

ALTER TABLE KurstillfalleLarare ADD FOREIGN KEY (kurstillfalle_id) REFERENCES Kurstillfalle (kurstillfalle_id);