// <auto-generated />
using System;
using Datalagring_Oskar_Videll.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Datalagring_Oskar_Videll.Infrastructure.Migrations
{
    [DbContext(typeof(DeltagareDBContext))]
    [Migration("20260128133111_KursTillfalleEntityAdded")]
    partial class KursTillfalleEntityAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Datalagring_Oskar_Videll.Infrastructure.Entities.DeltagareEntity", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Efternamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Fornamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Mellannamn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StatusTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefonnummer")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Email")
                        .HasName("PK_Deltagare_Email");

                    b.HasIndex("StatusTypeId");

                    b.HasIndex(new[] { "Email" }, "UQ_Deltagare_Email")
                        .IsUnique();

                    b.ToTable("Deltagare", null, t =>
                        {
                            t.HasCheckConstraint("CK_Deltagare_Email_NotEmpty", "LTRIM(RTRIM('Email')) <> ''");
                        });
                });

            modelBuilder.Entity("Datalagring_Oskar_Videll.Infrastructure.Entities.KursRegi_Entity", b =>
                {
                    b.Property<int>("KurstillfalleId")
                        .HasColumnType("integer");

                    b.Property<string>("DeltagareEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("KurstillfalleId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegiDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("KurstillfalleId", "DeltagareEmail")
                        .HasName("PK_KursRegi_KurstillfalleId");

                    b.HasIndex("DeltagareEmail");

                    b.HasIndex("KurstillfalleId1");

                    b.ToTable("KursRegi", (string)null);
                });

            modelBuilder.Entity("Datalagring_Oskar_Videll.Infrastructure.Entities.Kurs_Entity", b =>
                {
                    b.Property<string>("Kurskod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Beskrivning")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Kursnamn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Kurskod")
                        .HasName("PK_Kurs_Kurskod");

                    b.HasIndex(new[] { "Kursnamn" }, "UQ_Kurs_Kursnamn")
                        .IsUnique();

                    b.ToTable("Kurs", (string)null);
                });

            modelBuilder.Entity("Datalagring_Oskar_Videll.Infrastructure.Entities.KurstillfalleLarare_Entity", b =>
                {
                    b.Property<int>("KurstillfalleId")
                        .HasColumnType("integer");

                    b.Property<string>("LarareEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("KurstillfalleId1")
                        .HasColumnType("integer");

                    b.HasKey("KurstillfalleId", "LarareEmail")
                        .HasName("PK_KurstillfalleLarare_KurstillfalleId_LarareEmail");

                    b.HasIndex("KurstillfalleId1");

                    b.HasIndex("LarareEmail");

                    b.ToTable("KurstillfalleLarare", (string)null);
                });

            modelBuilder.Entity("Datalagring_Oskar_Videll.Infrastructure.Entities.Kurstillfalle_Entity", b =>
                {
                    b.Property<int>("KurstillfalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KurstillfalleId"));

                    b.Property<string>("KursKod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Kurskod")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("integer");

                    b.Property<int>("OrtId")
                        .HasColumnType("integer");

                    b.Property<int>("Ortid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Slutdatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Startdatum")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("KurstillfalleId")
                        .HasName("PK_KursTillfalle_KursId");

                    b.HasIndex("KursKod");

                    b.HasIndex("Kurskod");

                    b.HasIndex("OrtId");

                    b.HasIndex("Ortid");

                    b.ToTable("KursTillfalle", (string)null);
                });

            modelBuilder.Entity("Datalagring_Oskar_Videll.Infrastructure.Entities.Larare_Entity", b =>
                {
                    b.Property<string>("LarareEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("efternamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("fornamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("kompentens")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("mellannamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("LarareEmail")
                        .HasName("PK_Larare_LarareEmail");

                    b.HasIndex(new[] { "LarareEmail" }, "UQ_Larare_LarareEmail")
                        .IsUnique();

                    b.ToTable("Larare", null, t =>
                        {
                            t.HasCheckConstraint("CK_Larare_LarareEmail_NotEmpty", "LTRIM(RTRIM('LarareEmail')) <> ''");
                        });
                });

            modelBuilder.Entity("Datalagring_Oskar_Videll.Infrastructure.Entities.Ort_Entity", b =>
                {
                    b.Property<int>("OrtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrtId"));

                    b.Property<string>("OrtNamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("OrtId")
                        .HasName("PK_Ort_Ortid");

                    b.HasIndex(new[] { "OrtNamn" }, "UQ_Ort_Ortnamn")
                        .IsUnique();

                    b.ToTable("Ort", (string)null);
                });

            modelBuilder.Entity("Datalagring_Oskar_Videll.Infrastructure.Entities.Role_Entity", b =>
                {
                    b.Property<string>("RoleEmail")
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("RoleEmail")
                        .HasName("PK_Roles_Email");

                    b.HasIndex(new[] { "RoleName" }, "UQ_Roles_RoleName")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Datalagring_Oskar_Videll.Infrastructure.Entities.StatusTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("PK_StatusTypes_Id");

                    b.HasIndex(new[] { "StatusName" }, "UQ_StatusTypes_StatusName")
                        .IsUnique();

                    b.ToTable("StatusTypes", (string)null);
                });

            modelBuilder.Entity("DeltagareRoles", b =>
                {
                    b.Property<string>("DeltagareEmail")
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RoleEmail")
                        .HasColumnType("text");

                    b.HasKey("DeltagareEmail", "RoleEmail")
                        .HasName("PK_DeltagareRoles");

                    b.HasIndex("RoleEmail");

                    b.ToTable("DeltagareRoles", (string)null);
                });

            modelBuilder.Entity("Datalagring_Oskar_Videll.Infrastructure.Entities.DeltagareEntity", b =>
                {
                    b.HasOne("Datalagring_Oskar_Videll.Infrastructure.Entities.StatusTypeEntity", "StatusType")
                        .WithMany("Deltagare")
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Deltagare_StatusTypes_StatusTypeId");

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("Datalagring_Oskar_Videll.Infrastructure.Entities.KursRegi_Entity", b =>
                {
                    b.HasOne("Datalagring_Oskar_Videll.Infrastructure.Entities.DeltagareEntity", "Deltagare")
                        .WithMany()
                        .HasForeignKey("DeltagareEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datalagring_Oskar_Videll.Infrastructure.Entities.Kurstillfalle_Entity", null)
                        .WithMany("KursRegi")
                        .HasForeignKey("KurstillfalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KursRegi_KursTillfalle_KurstillfalleId");

                    b.HasOne("Datalagring_Oskar_Videll.Infrastructure.Entities.Kurstillfalle_Entity", "Kurstillfalle")
                        .WithMany()
                        .HasForeignKey("KurstillfalleId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deltagare");

                    b.Navigation("Kurstillfalle");
                });

            modelBuilder.Entity("Datalagring_Oskar_Videll.Infrastructure.Entities.KurstillfalleLarare_Entity", b =>
                {
                    b.HasOne("Datalagring_Oskar_Videll.Infrastructure.Entities.Kurstillfalle_Entity", null)
                        .WithMany("KurstillfalleLarare")
                        .HasForeignKey("KurstillfalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KurstillfalleLarare_KursTillfalle_KurstillfalleId");

                    b.HasOne("Datalagring_Oskar_Videll.Infrastructure.Entities.Kurstillfalle_Entity", "Kurstillfalle")
                        .WithMany()
                        .HasForeignKey("KurstillfalleId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datalagring_Oskar_Videll.Infrastructure.Entities.Larare_Entity", "Larare")
                        .WithMany("KurstillfalleLarare")
                        .HasForeignKey("LarareEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurstillfalle");

                    b.Navigation("Larare");
                });

            modelBuilder.Entity("Datalagring_Oskar_Videll.Infrastructure.Entities.Kurstillfalle_Entity", b =>
                {
                    b.HasOne("Datalagring_Oskar_Videll.Infrastructure.Entities.Kurs_Entity", null)
                        .WithMany()
                        .HasForeignKey("KursKod")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_KursTillfalle_Kurs_Kurskod");

                    b.HasOne("Datalagring_Oskar_Videll.Infrastructure.Entities.Kurs_Entity", "Kurs")
                        .WithMany()
                        .HasForeignKey("Kurskod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KursTillfalle_Kurs_Kurskod1");

                    b.HasOne("Datalagring_Oskar_Videll.Infrastructure.Entities.Ort_Entity", "Ort")
                        .WithMany()
                        .HasForeignKey("OrtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datalagring_Oskar_Videll.Infrastructure.Entities.Ort_Entity", null)
                        .WithMany()
                        .HasForeignKey("Ortid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_KursTillfalle_Ort_Ortid");

                    b.Navigation("Kurs");

                    b.Navigation("Ort");
                });

            modelBuilder.Entity("DeltagareRoles", b =>
                {
                    b.HasOne("Datalagring_Oskar_Videll.Infrastructure.Entities.DeltagareEntity", null)
                        .WithMany()
                        .HasForeignKey("DeltagareEmail")
                        .IsRequired()
                        .HasConstraintName("FK_DeltagareRoles_Deltagare_DeltagareEmail");

                    b.HasOne("Datalagring_Oskar_Videll.Infrastructure.Entities.Role_Entity", null)
                        .WithMany()
                        .HasForeignKey("RoleEmail")
                        .IsRequired()
                        .HasConstraintName("FK_DeltagareRoles_Roles_RoleEmail");
                });

            modelBuilder.Entity("Datalagring_Oskar_Videll.Infrastructure.Entities.Kurstillfalle_Entity", b =>
                {
                    b.Navigation("KursRegi");

                    b.Navigation("KurstillfalleLarare");
                });

            modelBuilder.Entity("Datalagring_Oskar_Videll.Infrastructure.Entities.Larare_Entity", b =>
                {
                    b.Navigation("KurstillfalleLarare");
                });

            modelBuilder.Entity("Datalagring_Oskar_Videll.Infrastructure.Entities.StatusTypeEntity", b =>
                {
                    b.Navigation("Deltagare");
                });
#pragma warning restore 612, 618
        }
    }
}
