// <auto-generated />
using System;
using DatalagringOskarVidell.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Datalagring_Oskar_Videll.Infrastructure.Migrations
{
    [DbContext(typeof(DeltagareDBContext))]
    [Migration("20260204163315_entity-deltagare-context")]
    partial class entitydeltagarecontext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.DeltagareEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Efternamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Fornamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Mellannamn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefonnummer")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id")
                        .HasName("PK_Deltagare_id");

                    b.HasIndex(new[] { "Email" }, "UQ_Deltagare_Email")
                        .IsUnique();

                    b.ToTable("Deltagare", null, t =>
                        {
                            t.HasCheckConstraint("CK_Deltagare_Email_NotEmpty", "LTRIM(RTRIM('Email')) <> ''");
                        });
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.KursRegi_Entity", b =>
                {
                    b.Property<Guid>("KursRegiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeltagareEmail")
                        .HasMaxLength(255)
                        .HasColumnType("uuid");

                    b.Property<string>("Kurs_EntityKurskod")
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("RegiDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("KursRegiId")
                        .HasName("PK_KursRegi_KursRegiId");

                    b.HasIndex("DeltagareEmail");

                    b.HasIndex("Kurs_EntityKurskod");

                    b.ToTable("KursRegi", (string)null);
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.Kurs_Entity", b =>
                {
                    b.Property<string>("Kurskod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Beskrivning")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Kursnamn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Kurskod")
                        .HasName("PK_Kurs_Kurskod");

                    b.HasIndex(new[] { "Kursnamn" }, "UQ_Kurs_Kursnamn")
                        .IsUnique();

                    b.ToTable("Kurs", (string)null);
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.KurstillfalleLarare_Entity", b =>
                {
                    b.Property<Guid>("KursTillfallenId")
                        .HasColumnType("uuid");

                    b.Property<string>("LarareEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("KursTillfallenId", "LarareEmail")
                        .HasName("PK_KurstillfalleLarare_KurstillfalleId_LarareEmail");

                    b.ToTable("KurstillfalleLarare", (string)null);
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.Kurstillfalle_Entity", b =>
                {
                    b.Property<Guid>("KursTillfallenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("KursKod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LarareEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("integer");

                    b.Property<Guid>("Ortid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Slutdatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Startdatum")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("KursTillfallenId")
                        .HasName("PK_KursTillfalle_KursId");

                    b.HasIndex("KursKod");

                    b.HasIndex("Ortid");

                    b.ToTable("KursTillfalle", (string)null);
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.Larare_Entity", b =>
                {
                    b.Property<string>("LarareEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Efternamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Fornamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Kompentens")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("KurstillfalleLarare_EntityKursTillfallenId")
                        .HasColumnType("uuid");

                    b.Property<string>("KurstillfalleLarare_EntityLarareEmail")
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Mellannamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("LarareEmail")
                        .HasName("PK_Larare_LarareEmail");

                    b.HasIndex("KurstillfalleLarare_EntityKursTillfallenId", "KurstillfalleLarare_EntityLarareEmail");

                    b.HasIndex(new[] { "LarareEmail" }, "UQ_Larare_LarareEmail")
                        .IsUnique();

                    b.ToTable("Larare", null, t =>
                        {
                            t.HasCheckConstraint("CK_Larare_LarareEmail_NotEmpty", "LTRIM(RTRIM('LarareEmail')) <> ''");
                        });
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.Ort_Entity", b =>
                {
                    b.Property<Guid>("OrtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("OrtNamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("OrtId")
                        .HasName("PK_Ort_Ortid");

                    b.HasIndex(new[] { "OrtNamn" }, "UQ_Ort_Ortnamn")
                        .IsUnique();

                    b.ToTable("Ort", (string)null);
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.KursRegi_Entity", b =>
                {
                    b.HasOne("DatalagringOskarVidell.Domain.Entities.DeltagareEntity", null)
                        .WithMany("Kursregi")
                        .HasForeignKey("DeltagareEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Deltagare_KursRegi_DeltagareEmail");

                    b.HasOne("DatalagringOskarVidell.Domain.Entities.Kurs_Entity", null)
                        .WithMany("Kurstillfallen")
                        .HasForeignKey("Kurs_EntityKurskod");
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.Kurstillfalle_Entity", b =>
                {
                    b.HasOne("DatalagringOskarVidell.Domain.Entities.Kurs_Entity", "Kurs")
                        .WithMany()
                        .HasForeignKey("KursKod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KursTillfalle_Kurs_KursKod");

                    b.HasOne("DatalagringOskarVidell.Domain.Entities.Ort_Entity", "Ort")
                        .WithMany()
                        .HasForeignKey("Ortid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KursTillfalle_Ort_Ortid");

                    b.Navigation("Kurs");

                    b.Navigation("Ort");
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.Larare_Entity", b =>
                {
                    b.HasOne("DatalagringOskarVidell.Domain.Entities.KurstillfalleLarare_Entity", null)
                        .WithMany("LarareRegi")
                        .HasForeignKey("KurstillfalleLarare_EntityKursTillfallenId", "KurstillfalleLarare_EntityLarareEmail");
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.DeltagareEntity", b =>
                {
                    b.Navigation("Kursregi");
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.Kurs_Entity", b =>
                {
                    b.Navigation("Kurstillfallen");
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.KurstillfalleLarare_Entity", b =>
                {
                    b.Navigation("LarareRegi");
                });
#pragma warning restore 612, 618
        }
    }
}
