// <auto-generated />
using Datalagring_Oskar_Videll.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Datalagring_Oskar_Videll.Infrastructure.Migrations
{
    [DbContext(typeof(DeltagareDBContext))]
    partial class DeltagareDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Datalagring_Oskar_Videll.Infrastructure.Entities.DeltagareEntity", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Efternamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Fornamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Mellannamn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefonnummer")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Email")
                        .HasName("PK_Deltagare_Email");

                    b.HasIndex(new[] { "Email" }, "UQ_Deltagare_Email")
                        .IsUnique();

                    b.ToTable("Deltagare", null, t =>
                        {
                            t.HasCheckConstraint("CK_Deltagare_Email_NotEmpty", "LTRIM(RTRIM('Email')) <> ''");
                        });
                });

            modelBuilder.Entity("Datalagring_Oskar_Videll.Infrastructure.Entities.Role_Entity", b =>
                {
                    b.Property<string>("RoleEmail")
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("RoleEmail")
                        .HasName("PK_Roles_Email");

                    b.HasIndex(new[] { "RoleName" }, "UQ_Roles_RoleName")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("DeltagareRoles", b =>
                {
                    b.Property<string>("DeltagareEmail")
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RoleEmail")
                        .HasColumnType("text");

                    b.HasKey("DeltagareEmail", "RoleEmail")
                        .HasName("PK_DeltagareRoles");

                    b.HasIndex("RoleEmail");

                    b.ToTable("DeltagareRoles", (string)null);
                });

            modelBuilder.Entity("DeltagareRoles", b =>
                {
                    b.HasOne("Datalagring_Oskar_Videll.Infrastructure.Entities.DeltagareEntity", null)
                        .WithMany()
                        .HasForeignKey("DeltagareEmail")
                        .IsRequired()
                        .HasConstraintName("FK_DeltagareRoles_Deltagare_DeltagareEmail");

                    b.HasOne("Datalagring_Oskar_Videll.Infrastructure.Entities.Role_Entity", null)
                        .WithMany()
                        .HasForeignKey("RoleEmail")
                        .IsRequired()
                        .HasConstraintName("FK_DeltagareRoles_Roles_RoleEmail");
                });
#pragma warning restore 612, 618
        }
    }
}
