// <auto-generated />
using System;
using DatalagringOskarVidell.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Datalagring_Oskar_Videll.Infrastructure.Migrations
{
    [DbContext(typeof(DeltagareDBContext))]
    partial class DeltagareDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.DeltagareEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Efternamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Fornamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Mellannamn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefonnummer")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("character varying(13)");

                    b.HasKey("ID")
                        .HasName("PK_Deltagare_ID");

                    b.HasIndex(new[] { "Email" }, "UQ_Deltagare_Email")
                        .IsUnique();

                    b.ToTable("Deltagare", null, t =>
                        {
                            t.HasCheckConstraint("CK_Deltagare_Email_NotEmpty", "LTRIM(RTRIM('Email')) <> ''");
                        });
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.KursRegi_Entity", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Antagen")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegiDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ID", "Antagen")
                        .HasName("PK_RegiDeltagare_ID_Antagen");

                    b.HasIndex("Antagen");

                    b.ToTable("KursRegi", (string)null);
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.Kurs_Entity", b =>
                {
                    b.Property<string>("Kurskod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Beskrivning")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Kursnamn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Kurskod")
                        .HasName("PK_Kurs_Kurskod");

                    b.HasIndex(new[] { "Kursnamn" }, "UQ_Kurs_Kursnamn")
                        .IsUnique();

                    b.ToTable("Kurs", (string)null);
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.KurstillfalleLarare_Entity", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uuid");

                    b.Property<string>("Larare")
                        .HasColumnType("character varying(255)");

                    b.HasKey("ID", "Larare")
                        .HasName("PK_RegiLarare_ID_Larare");

                    b.HasIndex("Larare");

                    b.ToTable("LarareRegi", (string)null);
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.Kurstillfalle_Entity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("KursKodID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("integer");

                    b.Property<int>("Ortid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Slutdatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Startdatum")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID")
                        .HasName("PK_KursTillfalle_KursId");

                    b.HasIndex("KursKodID");

                    b.HasIndex("Ortid");

                    b.ToTable("KursTillfalle", (string)null);
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.Larare_Entity", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Efternamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Fornamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Kompentens")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Mellannamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Email")
                        .HasName("PK_Larare_LarareEmail");

                    b.HasIndex(new[] { "Email" }, "UQ_Larare_LarareEmail")
                        .IsUnique();

                    b.ToTable("Larare", null, t =>
                        {
                            t.HasCheckConstraint("CK_Larare_LarareEmail_NotEmpty", "LTRIM(RTRIM('LarareEmail')) <> ''");
                        });
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.Ort_Entity", b =>
                {
                    b.Property<int>("OrtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrtId"));

                    b.Property<string>("OrtNamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("OrtId")
                        .HasName("PK_Ort_Ortid");

                    b.HasIndex(new[] { "OrtNamn" }, "UQ_Ort_Ortnamn")
                        .IsUnique();

                    b.ToTable("Ort", (string)null);
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.KursRegi_Entity", b =>
                {
                    b.HasOne("DatalagringOskarVidell.Domain.Entities.DeltagareEntity", "DeltagareRegi")
                        .WithMany()
                        .HasForeignKey("Antagen")
                        .IsRequired();

                    b.HasOne("DatalagringOskarVidell.Domain.Entities.Kurstillfalle_Entity", "Kurstillfallen")
                        .WithMany()
                        .HasForeignKey("ID")
                        .IsRequired();

                    b.Navigation("DeltagareRegi");

                    b.Navigation("Kurstillfallen");
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.KurstillfalleLarare_Entity", b =>
                {
                    b.HasOne("DatalagringOskarVidell.Domain.Entities.Kurstillfalle_Entity", "Kurstillfallen")
                        .WithMany()
                        .HasForeignKey("ID")
                        .IsRequired();

                    b.HasOne("DatalagringOskarVidell.Domain.Entities.Larare_Entity", "LarareRegi")
                        .WithMany()
                        .HasForeignKey("Larare")
                        .IsRequired();

                    b.Navigation("Kurstillfallen");

                    b.Navigation("LarareRegi");
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.Kurstillfalle_Entity", b =>
                {
                    b.HasOne("DatalagringOskarVidell.Domain.Entities.Kurs_Entity", "Kurs")
                        .WithMany("Kurstillfallen")
                        .HasForeignKey("KursKodID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_KursTillfalle_Kurs_KursKod");

                    b.HasOne("DatalagringOskarVidell.Domain.Entities.Ort_Entity", "Ort")
                        .WithMany("Kurstillfallen")
                        .HasForeignKey("Ortid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_KursTillfalle_Ort_Ortid");

                    b.Navigation("Kurs");

                    b.Navigation("Ort");
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.Kurs_Entity", b =>
                {
                    b.Navigation("Kurstillfallen");
                });

            modelBuilder.Entity("DatalagringOskarVidell.Domain.Entities.Ort_Entity", b =>
                {
                    b.Navigation("Kurstillfallen");
                });
#pragma warning restore 612, 618
        }
    }
}
